version: '3.8'

services:
  rag_ui:
    image: askhem/rag-ui:latest
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://localhost:8000}
    networks:
      - rag-network
    depends_on:
      - rag_backend

  rag_backend:
    image: askhem/rag-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_AUTH_SOURCE=${MONGODB_AUTH_SOURCE}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_COLLECTION_NAME=${MONGO_COLLECTION_NAME}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      - CACHE_ENABLED=${CACHE_ENABLED}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE}
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge