name: rag-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - faiss-cpu
  - pip
  - numpy=1.24.3
  - pip:
    - python-multipart
    - openai==1.57.0
    - environs==11.2.1
    - langchain
    - langchain-community==0.3.12
    - langchain-mongodb
    - langchain-huggingface
    - motor==3.6.0
    - sentence-transformers==3.3.1
    - fastapi==0.115.6
    - "uvicorn[standard]==0.20.0"
    - python-multipart==0.0.9
    - pypdf==5.1.0
    - unstructured==0.16.11
    - tiktoken==0.8.0
    - requests==2.32.3
    - python-dotenv==1.0.0
    - pymongo==4.9.2
    - pymongo[srv]
    - transformers>=4.36.2
    - torch>=2.2.0
    - beautifulsoup4==4.12.3